export const TIPOS_ACCION_INFANCIA = [
  "VER_FICHA_NINO",
  "VALORAR_HITO",
  "REGISTRAR_PESO_TALLA",
  "CALCULAR_EDAD_CORREGIDA",
  "VERIFICAR_ESQUEMA_VACUNACION",
  "DETECTAR_SEÑAL_ALARMA",
  "DERIVAR_A_ESPECIALISTA",
  "ACTIVAR_RUTA_PROTECCION",
  "REGISTRAR_SEGUIMIENTO",
] as const;

export const RESULTADOS_INFANCIA = {
  SEGUIMIENTO_NORMAL: "SEGUIMIENTO_NORMAL",
  DERIVAR_ESPECIALISTA: "DERIVAR_ESPECIALISTA",
  ACTIVAR_RUTA_PROTECCION: "ACTIVAR_RUTA_PROTECCION",
} as const;
