export const TIPOS_ACCION_ENFERMERIA = [
  "VER_FICHA_PACIENTE",
  "VERIFICAR_ORDEN_MEDICA",
  "VERIFICAR_ALERGIA",
  "TOMAR_SIGNOS_VITALES",
  "PREPARAR_DOSIS",
  "REGISTRAR_ADMINISTRACION",
  "RECHAZAR_ADMINISTRACION",
  "REPORTAR_REACCION_ADVERSA",
  "ESCALAR_A_SUPERVISOR",
] as const;

export const RESULTADOS_ENFERMERIA = {
  ADMINISTRAR_CORRECTO: "ADMINISTRAR_CORRECTO",
  NO_ADMINISTRAR_CORRECTO: "NO_ADMINISTRAR_CORRECTO",
} as const;
