export const TIPOS_ACCION_ODONTOLOGIA = [
  "INTERROGAR_PACIENTE",
  "EXAMINAR_PACIENTE",
  "APLICAR_REVELADOR_PLACA",
  "SOLICITAR_RADIOGRAFIA",
  "GUARDAR_HISTORIA",
  "CERRAR_HISTORIA",
] as const;

/** Resultado del caso = la remisión que decide el estudiante al cerrar la historia (sección XI). */
export const RESULTADOS_ODONTOLOGIA = {
  ATENCION_EN_CONSULTA: "ATENCION_EN_CONSULTA",
  REMISION_ESPECIALISTA: "REMISION_ESPECIALISTA",
  INTERCONSULTA_MEDICA: "INTERCONSULTA_MEDICA",
} as const;
